print("***********************STUDENT DETAILS *******************************")
Name=input("Enter your name :")
print("student Name is :",Name)
Collage=input("Enter your collage name :")
print("Collage Name is :",Collage)
Branch=input("Enter your branch :")
print("Branch is :",Branch)
Rollno=int(input("Enter your Roll NO :"))
print("Roll No is :",Rollno)
StudentNo=int(input("Enter your Mobile No :"))
print("Moblie No is :",StudentNo)
Address=input("Enter your address : ")
print("Address is :",Address)
Age=int(input("Enter your age :"))
print("Age is :",Age)
Year=input("Enter your year :")


print("********************* Type ***************************************")
print(type(Name))
print(type(Collage))
print(type(Branch)) 
print(type(Rollno))
print(type(StudentNo))
print(type(Address))
print(type(Age))
print(type(Year))
